# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a3aebb2290aa68cf6614c707c226f20fc194b8c361e16c891ad8ce1afd5258f73ded0a866bb11c26fad7e680e38319ded54847b1789f1d49f8571b10e2ece7

test:
  secret_key_base: 270585a92bfc48d0f3219b532a1ac3825fa159f6639e7c1cb8cda44274a622f88961b36137f33364e8f4e58d3d1e68064e863b1a58b3180c0330c500f1fb3044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
